version: '3.4'
services:
  ia:
    image: ${DOCKER_REGISTRY-}ia
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ia
    restart: always
    network_mode: host
    volumes:
      - ./downloads:/downloads